### ISSUE TITLE
Ask for help: How to use multi GPUs? All input tensors must be on the same device. Received cuda:3 and cuda:2

### ISSUE THREAD

**Issue by starrywintersky** [lucidrains/vit-pytorch#131]
I tried to use multi gpus with data_parallel, but got an error: 

File "main_transformer_classification.py", line 45, in train
    out, att_map = self.model(data)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/local/lib64/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in replica 0 on device 0.
Original Traceback (most recent call last):
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/mnt/group-ai-medical-sz/private/starryzwang/code/ft_local/ft_local/ssh_loading_focal_0707/models/vit.py", line 33, in forward
    out, att_map = self.att_vit(img)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/vit_pytorch/recorder.py", line 53, in forward
    attns = torch.stack(self.recordings, dim = 1)
RuntimeError: All input tensors must be on the same device. Received cuda:3 and cuda:2

**Comment by lucidrains** [comment]
@starrywintersky Hi Ziyuan! Do you want to try 0.20.1 and see if that solves your issue? https://github.com/lucidrains/vit-pytorch/commit/22da26fa4b7d98c2a936b48c1b1dcf83c404dfb8

**Comment by wangqingbin** [comment]
> I tried to use multi gpus with data_parallel, but got an error:
> 
> File "main_transformer_classification.py", line 45, in train
> out, att_map = self.model(data)
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
> outputs = self.parallel_apply(replicas, inputs, kwargs)
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
> return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
> output.reraise()
> File "/usr/local/lib64/python3.6/site-packages/torch/_utils.py", line 395, in reraise
> raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in replica 0 on device 0.
> Original Traceback (most recent call last):
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
> output = module(*input, **kwargs)
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/mnt/group-ai-medical-sz/private/starryzwang/code/ft_local/ft_local/ssh_loading_focal_0707/models/vit.py", line 33, in forward
> out, att_map = self.att_vit(img)
> File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
> result = self.forward(*input, **kwargs)
> File "/usr/local/lib/python3.6/site-packages/vit_pytorch/recorder.py", line 53, in forward
> attns = torch.stack(self.recordings, dim = 1)
> RuntimeError: All input tensors must be on the same device. Received cuda:3 and cuda:2

Have you solved this problem? I meet the save one.

**Comment by lucidrains** [comment]
@wangqingbin try upgrading `pip install --upgrade`

**Comment by graycrown** [comment]
Is there any solution for this problem, I met the same problem
